### ISSUE TITLE
opsgenie api supports alias in alert.create(), but this library forbids it

### ISSUE THREAD

**Issue by gschlossnagle** [HurricaneLabs/opsgenie-python#1]
The opsgenie API allows you to create an alert with an alias in the create statement, but trying that here results in:

ValueError: You specified the ID parameter 'alias'.  This will causethe API to update the specified alert instead of creating one.  Did you mean tocall AlertResource.update() instead?

The API should only error in create if 'id' is passed.

**Comment by lwcolton** [comment]
Thanks I'll look into this

**Comment by lwcolton** [comment]
Fixed in e9606e02cf0800d3ef684cb0c3552672a04bc486
